### ISSUE TITLE
iprep.yml Invalid Yaml File

### ISSUE THREAD

**Issue by austinJayIves** [dtag-dev-sec/listbot#2] opened 2019-10-03 21:22 UTC
Currently, iprep.yml is an invalid yaml file. This is currently breaking Logstash TPOTCE configurations.

Steps to reproduce:
1. Input `https://raw.githubusercontent.com/dtag-dev-sec/listbot/master/iprep.yaml` into `https://codebeautify.org/yaml-validator/`

**Comment by t3chn0m4g3** [comment] 2019-10-04 08:19
Thanks for reporting, but since this is just a translation map which only happens to have the `yaml` extension, it is built agaisnt the requirements of [logstash translation maps](https://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html#plugins-filters-translate-exact).

Based on your info we cannot reproduce any errors and since it is working perfectly fine I am closing this.

**Closed as completed by t3chn0m4g3** 2019-10-04 08:19 UTC
